### ISSUE TITLE
No date attribute

### ISSUE THREAD

**Issue by Qpernicus** [xirixiz/homeassistant-afvalwijzer#124]
## Version of the custom_component
 5.2.1

## Configuration

Config is bonestock with my own postal code etc. Worked in 5.2.0 flawless. Made no changes when updating to 5.2.1. Using Mijnafvalwijzer, no other provider. 

Add your logs here.

```

## Describe the bug
A clear and concise description of what the bug is.

I updated from 5.2.0 (no problems) to 5.2.1 and after the required restart got this:

Logger: homeassistant.helpers.entity
Source: custom_components/afvalwijzer/sensor_provider.py:95
First occurred: 11:20:06 (5 occurrences) 
Last logged: 11:20:06

Update for sensor.afvalwijzer_gft fails
Update for sensor.afvalwijzer_pmd fails
Update for sensor.afvalwijzer_restafval fails
Update for sensor.afvalwijzer_papier fails
Update for sensor.afvalwijzer_textiel fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_provider.py", line 95, in async_update
    waste_data_provider[self.waste_type].date(),
AttributeError: 'datetime.date' object has no attribute 'date'



## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```
